server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh              #路由id，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001     #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
          - Path=/payment8001/**       #断言，路径相匹配的进行路由
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由

eureka:
  client:
    register-with-eureka: true #false表示不向注册中心注册自己
    fetchRegistry: true #false表示自己就是注册中心，我的职责就是维护服务实例，不需要去检索服务
    service-url: #设置与eureka server服务的交换地址，查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    hostname: cloud-gateway-service
